-- MySQL Script generated by MySQL Workbench
-- Thu Mar 22 15:37:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema instituto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `instituto` ;

-- -----------------------------------------------------
-- Schema instituto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `instituto` DEFAULT CHARACTER SET utf8 ;
USE `instituto` ;

-- -----------------------------------------------------
-- Table `instituto`.`tutor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instituto`.`tutor` ;

CREATE TABLE IF NOT EXISTS `instituto`.`tutor` (
  `dni` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instituto`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instituto`.`alumno` ;

CREATE TABLE IF NOT EXISTS `instituto`.`alumno` (
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `lugarNacimiento` VARCHAR(45) NULL,
  `tutor_dni` INT NULL,
  PRIMARY KEY (`dni`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC),
  INDEX `fk_alumno_tutor1_idx` (`tutor_dni` ASC),
  CONSTRAINT `fk_alumno_tutor1`
    FOREIGN KEY (`tutor_dni`)
    REFERENCES `instituto`.`tutor` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instituto`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instituto`.`curso` ;

CREATE TABLE IF NOT EXISTS `instituto`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `anio` INT NOT NULL,
  PRIMARY KEY (`idcurso`),
  UNIQUE INDEX `idcurso_UNIQUE` (`idcurso` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instituto`.`alumnoxcurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instituto`.`alumnoxcurso` ;

CREATE TABLE IF NOT EXISTS `instituto`.`alumnoxcurso` (
  `alumno_dni` INT NOT NULL,
  `curso_idcurso` INT NOT NULL,
  `anio` INT NOT NULL,
  PRIMARY KEY (`alumno_dni`, `curso_idcurso`),
  INDEX `fk_alumno_has_curso_curso1_idx` (`curso_idcurso` ASC),
  INDEX `fk_alumno_has_curso_alumno_idx` (`alumno_dni` ASC),
  CONSTRAINT `fk_alumno_has_curso_alumno`
    FOREIGN KEY (`alumno_dni`)
    REFERENCES `instituto`.`alumno` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_curso_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `instituto`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instituto`.`asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instituto`.`asistencia` ;

CREATE TABLE IF NOT EXISTS `instituto`.`asistencia` (
  `idasistencia` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `tipo` ENUM('clase', 'edFisica', 'clase+edFisica') NOT NULL,
  `valor` ENUM('1', '1/2') NOT NULL,
  `alumnoxcurso_alumno_dni` INT NOT NULL,
  `alumnoxcurso_curso_idcurso` INT NOT NULL,
  `justificada` TINYINT(2) NOT NULL,
  PRIMARY KEY (`idasistencia`, `alumnoxcurso_alumno_dni`, `alumnoxcurso_curso_idcurso`),
  UNIQUE INDEX `idasistencia_UNIQUE` (`idasistencia` ASC),
  INDEX `fk_asistencia_alumnoxcurso1_idx` (`alumnoxcurso_alumno_dni` ASC, `alumnoxcurso_curso_idcurso` ASC),
  CONSTRAINT `fk_asistencia_alumnoxcurso1`
    FOREIGN KEY (`alumnoxcurso_alumno_dni` , `alumnoxcurso_curso_idcurso`)
    REFERENCES `instituto`.`alumnoxcurso` (`alumno_dni` , `curso_idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instituto`.`preceptor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instituto`.`preceptor` ;

CREATE TABLE IF NOT EXISTS `instituto`.`preceptor` (
  `dni` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
